<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3508" started-at="2019-12-29T13:20:07Z" finished-at="2019-12-29T13:20:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3508" started-at="2019-12-29T13:20:07Z" finished-at="2019-12-29T13:20:10Z">
      <class name="testscripts.TC002_POST_CustomerInfo">
        <test-method status="PASS" signature="intailize(java.lang.reflect.Method)[pri:0, instance:testscripts.TC002_POST_CustomerInfo@57baeedf]" name="intailize" is-config="true" duration-ms="226" started-at="2019-12-29T18:50:07Z" finished-at="2019-12-29T18:50:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testscripts.TC002_POST_CustomerInfo.registerCustomer()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intailize -->
        <test-method status="FAIL" signature="registerCustomer()[pri:0, instance:testscripts.TC002_POST_CustomerInfo@57baeedf]" name="registerCustomer" duration-ms="2820" started-at="2019-12-29T18:50:07Z" finished-at="2019-12-29T18:50:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [201] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [201] but found [200]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at testscripts.TC002_POST_CustomerInfo.registerCustomer(TC002_POST_CustomerInfo.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerCustomer -->
        <test-method status="PASS" signature="clear(org.testng.ITestResult)[pri:0, instance:testscripts.TC002_POST_CustomerInfo@57baeedf]" name="clear" is-config="true" duration-ms="433" started-at="2019-12-29T18:50:10Z" finished-at="2019-12-29T18:50:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=registerCustomer status=FAILURE method=TC002_POST_CustomerInfo.registerCustomer()[pri:0, instance:testscripts.TC002_POST_CustomerInfo@57baeedf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clear -->
      </class> <!-- testscripts.TC002_POST_CustomerInfo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
